### Import Packages

In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline
sns.set(color_codes=True)
import glob
import missingno as msno
from scipy import stats

import warnings
warnings.filterwarnings('ignore')

### Read in the Dataset

In [2]:
# Point to data files location
path = "./scraper/data/6_23_2025/"
all_files = glob.glob(path + "*.json")

# Read all files into single dataframe
df_list = []
for file in all_files:
    df = pd.read_json(file)
    df_list.append(df)

# ignore_index resets index of combined DF to prevent index duplicates
raw_df = pd.concat(df_list, ignore_index=True) 

# Display entire data frame
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

# Examine and excerpt of data
raw_df.head(5)

,stockNumber,vin,year,make,model,body,trim,basePrice,originalPrice,hasPriceDrop,mileage,storeId,storeName,storeCity,state,stateAbbreviation,distance,averageRating,numberOfReviews,repairPalData,isNewArrival,isTransferable,features,highlightedFeatures,highlights,lastMadeSaleableDate,transferFee,transferTags,transferText,transferType,minEstimatedTransferDurationInDays,maxEstimatedTransferDurationInDays,transferTimesUnavailable,exteriorColor,interiorColor,normalizedExteriorColor,normalizedInteriorColor,transmission,review,numberOfFavorites,isSaleable,isComingSoon,isReserved,mpgCity,mpgHighway,originalBatteryRangeInMiles,cylinders,driveTrain,engineType,fuelType,horsepower,horsepowerRpm,engineSize,engineTorque,engineTorqueRpm,priorUseDescriptions,isAvailableToTransact,recommendationType,bestFinanceDecision,store,featureScore,vehicleSize,packages,types,series,isSavedCar,heroImageUrl,heroThumbnailImageUrl,isEVTaxCreditEligible
0,27461478,5NPEG4JA8NH134099,2022,Hyundai,Sonata,4D Sedan,SE,19998,NaN,False,56782,7298,Roswell,Roswell,Georgia,GA,2108.0,4.200000,5,NaN,False,True,"[Rear Defroster, Overhead Airbags, Auxiliary A...","Rear View Camera,Auxiliary Audio Input,Alloy W...","[singleOwner, warranty, fuelEfficient, advance...",2025-06-12T20:56:13.565Z,1999.0,"[GeneratedByCps, Paid]",$1999 Shipping,shipping-from,9.0,22.0,False,Gray,Gray,NaN,NaN,Automatic,NaN,0,True,False,False,28.0,38.0,NaN,4,Front Wheel Drive,Gas,NaN,191.0,6100.0,2.5L,181.0,4000.0,"[{'id': 20, 'name': 'Leased Vehicle', 'descrip...",True,NaN,NaN,"{'id': 7298, 'name': 'Roswell', 'city': None, ...",3.0,NaN,[],NaN,None,False,https://img2.carmax.com/assets/27461478/hero.j...,NaN,False
1,26070459,JTDEPMAE5NJ210260,2022,Toyota,Corolla,4D Sedan,LE,20998,NaN,False,33730,7298,Roswell,Roswell,Georgia,GA,2108.0,4.500000,22,NaN,False,True,"[Power Windows, Power Locks, Air Conditioning,...","Rear View Camera,Auxiliary Audio Input,Overhea...","[warranty, fuelEfficient, advancedFeatures]",2025-06-12T20:53:33.311Z,1999.0,"[GeneratedByCps, Paid]",$1999 Shipping,shipping-from,9.0,22.0,False,Blue,Black,NaN,NaN,Automatic,NaN,0,True,False,False,30.0,38.0,NaN,4,Front Wheel Drive,Gas,NaN,139.0,6100.0,1.8L,126.0,3900.0,"[{'id': 10, 'name': 'Fleet', 'description': 'T...",True,NaN,NaN,"{'id': 7298, 'name': 'Roswell', 'city': None, ...",7.0,NaN,[],NaN,None,False,https://img2.carmax.com/assets/26070459/hero.j...,NaN,False
2,27175122,3GCUDFE80RG128481,2024,Chevrolet,Silverado 1500,4D Crew Cab,LT Trail Boss,51998,NaN,False,58240,7298,Roswell,Roswell,Georgia,GA,2108.0,5.000000,1,NaN,False,True,"[Power Locks, Auxiliary Audio Input, AM/FM Ste...","Z71 Package,4WD/AWD,Leather Seats,BOSE Sound S...","[singleOwner, advancedFeatures, premiumAudio]",2025-06-20T21:39:32.178Z,1999.0,"[GeneratedByCps, Paid]",$1999 Shipping,shipping-from,9.0,22.0,False,Black,Black,NaN,NaN,Automatic,NaN,0,True,False,False,23.0,27.0,NaN,6,Four Wheel Drive,Diesel,NaN,305.0,3750.0,3.0L,495.0,2750.0,[],True,NaN,NaN,"{'id': 7298, 'name': 'Roswell', 'city': None, ...",10.0,NaN,"[Convenience Package, Z71 Package]",NaN,None,False,https://img2.carmax.com/assets/27175122/hero.j...,NaN,False
3,27072297,1V2WE2CA5PC229115,2023,Volkswagen,Atlas Cross Sport,4D Sport Utility,SE w/Tech,32998,NaN,False,15895,7298,Roswell,Roswell,Georgia,GA,2108.0,5.000000,2,NaN,False,True,"[Alloy Wheels, 20 Inch Plus Wheels, Power Lock...","Technology Package,Leatherette Seats,Satellite...","[singleOwner, lowMiles, warranty, advancedFeat...",2025-05-28T20:50:22.353Z,1999.0,"[GeneratedByCps, Paid]",$1999 Shipping,shipping-from,9.0,22.0,False,Black,Black,NaN,NaN,Automatic,NaN,0,True,False,False,18.0,24.0,NaN,6,Front Wheel Drive,Gas,NaN,276.0,6200.0,3.6L,266.0,3600.0,"[{'id': 10, 'name': 'Fleet', 'description': 'T...",True,NaN,NaN,"{'id': 7298, 'name': 'Roswell', 'city': None, ...",5.0,NaN,[Technology Package],NaN,None,False,https://img2.carmax.com/assets/27072297/hero.j...,NaN,False
4,27386026,58AGZ1B12MU110647,2021,Lexus,ES 350,4D Sedan,F-Sport,35998,NaN,False,26900,7298,Roswell,Roswell,Georgia,GA,2108.0,4.333333,6,NaN,False,True,"[Power Windows, Traction Control, ABS Brakes, ...","Leatherette Seats,Pioneer Sound System,Parking...","[singleOwner, lowMilesPerYear, warranty, advan...",2025-06-13T20:59:37.45Z,1999.0,"[GeneratedByCps, Paid]",$1999 Shipping,shipping-from,9.0,22.0,False,Black,Red,NaN,NaN,Automatic,NaN,0,True,False,False,22.0,31.0,NaN,6,Front Wheel Drive,Gas,NaN,302.0,6600.0,3.5L,267.0,4700.0,"[{'id': 20, 'name': 'Leased Vehicle', 'descrip...",True,NaN,NaN,"{'id': 7298, 'name': 'Roswell', 'city': None, ...",7.0,NaN,[],NaN,ES,False,https://img2.carmax.com/assets/27386026/hero.j...,NaN,False

### Drop Duplicate Rows

In [3]:
# Make a copy of the original dataframe
df = raw_df.copy()

# Check rows with duplicate VINS and drop
df = df.drop_duplicates(subset=['vin'], keep='first')

### Convert Engine Size to Numeric Datatype

In [4]:
# Convert Engine Size into a numeric feature by removing the L and changing datatype
df['engineSize'] = df['engineSize'].str.replace('L', '', regex=False)
df['engineSize'] = pd.to_numeric(df['engineSize'])

print(df['engineSize'].dtype)

float64

### Drop Outliers in Mileage column (only one)

In [5]:
# Remove all outliers in the mileage column based on a zscore of 3
df = df[np.abs(stats.zscore(df['mileage'])) < 3]

print("DataFrame Shape After:", df.shape)

DataFrame Shape After: (86159, 69)

### Remove Unnecessary Columns Based on Previous Analyses

In [6]:
# Store irrelevant features into an array
irrelevant_features = [
    'stockNumber', 'hasPriceDrop', 'distance', 'isNewArrival',
    'isTransferable', 'lastMadeSaleableDate', 'transferFee', 'transferTags',
    'transferText', 'transferType', 'minEstimatedTransferDurationInDays', 'maxEstimatedTransferDurationInDays',
    'transferTimesUnavailable', 'isSaleable', 'isComingSoon', 'isReserved',
    'isAvailableToTransact', 'recommendationType', 'bestFinanceDecision', 'isSavedCar',
    'heroImageUrl', 'heroThumbnailImageUrl'
]

# Leave only state to represent location
location_features = [
    'store', 'storeId', 'storeName', 'storeCity', 'stateAbbreviation'
]

# Remove missing values features
missing_value_features = [
    'review', 'repairPalData', 'types', 'vehicleSize', 
    'normalizedExteriorColor', 'normalizedInteriorColor', 'fuelType',
    'originalBatteryRangeInMiles', 'originalPrice', 'series'
]

# Drop features being analyzed in a different file
complex_features = [
    'features', 'highlightedFeatures', 'highlights',
    'priorUseDescriptions', 'packages'
]

# Drop irrelevant feature arrays defined above
df = df.drop(columns = irrelevant_features, axis = 1)
df = df.drop(columns = location_features, axis = 1)
df = df.drop(columns = missing_value_features, axis = 1)
df = df.drop(columns = complex_features, axis = 1)
df = df.drop(columns = ['isEVTaxCreditEligible'], axis = 1)
df = df.drop(columns = ['numberOfFavorites'], axis = 1)

# Remove missing value rows for the following features
missing_value_rows = [
    'interiorColor', 'exteriorColor'
]
df.dropna(subset=missing_value_rows, how='any',inplace=True)

# Leave predictable missing value rows
# 'driveTrain', 'engineSize', 'engineType', 'body', 'transmission'

# # Other missing value rows
# missing_value_rows_2 = [
#     'engineTorqueRpm', 'horsepowerRpm', 'engineTorque', 'horsepower', 
#     'mpgCity', 'mpgHighway', 'engineType'
# ]

# df.dropna(subset=missing_value_rows_2, how='any', inplace=True)

print("DataFrame Shape:", df.shape)

DataFrame Shape: (86025, 25)

In [7]:
# Use method to display a list of missing values and their percentages

# credit: https://www.kaggle.com/willkoehrsen/start-here-a-gentle-introduction. 

def missing_values_table(df):
    # Total missing values
    mis_val = df.isnull().sum()
    
    # Percentage of missing values
    mis_val_percent = 100 * df.isnull().sum() / len(df)
    
    # Make a table with the results
    mis_val_table = pd.concat([mis_val, mis_val_percent], axis=1)
    
    # Rename the columns
    mis_val_table_ren_columns = mis_val_table.rename(
    columns = {0 : 'Missing Values', 1 : '% of Total Values'})
    
    # Sort the table by percentage of missing descending
    mis_val_table_ren_columns = mis_val_table_ren_columns[
        mis_val_table_ren_columns.iloc[:,1] != 0].sort_values(
    '% of Total Values', ascending=False).round(2)
    
    # Print some summary information
    print ("Your selected dataframe has " + str(df.shape[1]) + " columns.\n"      
        "There are " + str(mis_val_table_ren_columns.shape[0]) +
            " columns that have missing values.")
    
    # Return the dataframe with missing information
    return mis_val_table_ren_columns

In [8]:
# Apply missing values table method on the dataframe
missing_vals = missing_values_table(df)
missing_vals

Your selected dataframe has 25 columns.
There are 12 columns that have missing values.

                 Missing Values  % of Total Values
featureScore               8760              10.18
trim                       7344               8.54
engineTorqueRpm            5838               6.79
horsepowerRpm              5070               5.89
engineTorque               4542               5.28
horsepower                 4364               5.07
mpgCity                    3441               4.00
mpgHighway                 3438               4.00
driveTrain                  264               0.31
engineSize                   10               0.01
engineType                    2               0.00
body                          1               0.00

### Impute Feature Scores and Trims

In [9]:
# Regressor for Numerical Values
# Classifier for Categorical Values
from lightgbm import LGBMRegressor, LGBMClassifier

In [10]:
# Display columns in df with missing vals
cols_with_nans = [x for x in df if df[x].isnull().sum() > 0]
cols_with_nans

['body',
 'trim',
 'mpgCity',
 'mpgHighway',
 'driveTrain',
 'engineType',
 'horsepower',
 'horsepowerRpm',
 'engineSize',
 'engineTorque',
 'engineTorqueRpm',
 'featureScore']

In [11]:
# Divide into categorical and numeric columns
num_cols = [col for col in df[cols_with_nans].select_dtypes(exclude='O')]
cat_cols = [col for col in df[cols_with_nans].select_dtypes(include='O')]

print("Numeric Columns: \n", num_cols)
print("Categorical Columns: \n", cat_cols)

Numeric Columns:
 ['mpgCity', 'mpgHighway', 'horsepower', 'horsepowerRpm', 'engineSize', 'engineTorque', 'engineTorqueRpm', 'featureScore']
Categorical Columns:
 ['body', 'trim', 'driveTrain', 'engineType']

In [12]:

def factorize(data):
    # Factorize categorical data so its represented as integers
    for cat_col in data.select_dtypes(include='O'):
        data[cat_col] = pd.factorize(data[cat_col])[0]
    return data

def create_splits(data, col):
    # Train Test split on null values present
    train = data[data['is_nan'] == 0]
    test = data[data['is_nan'] == 1]
    X_train = train.drop([col, 'is_nan'], axis=1)
    y_train = train[col]
    X_test = test.drop([col, 'is_nan'], axis=1)
    return X_train, y_train, X_test

def train_predict(mode, X_train, y_train, X_test):
    if mode == 'regression':
        model = LGBMRegressor()
    else :
        model = LGBMClassifier()
    model.fit(X_train, y_train)
    y_pred = model.predict(X_test)
    return y_pred


def impute_missing(df, col_list, mode):
    for col in col_list:
        print("Column Examined: ", col)
        if df[col].isnull().sum() > int(len(df)/2):
            df.drop(col, axis=1, inplace=True)
            print(f'Dropped {col} because it had over 50% missing values')
        else:
            data = df.copy()
            # Reset Indexes
            data = data.reset_index(drop=True)
            nan_ixs = np.where(data[col].isna())[0]
            data['is_nan'] = 0
            data.loc[nan_ixs, 'is_nan'] = 1
            X = data.drop([col], axis=1)
            y = data[col]
            X = factorize(X)
            data = X.join(y)
            X_train, y_train, X_test = create_splits(data, col)
            y_pred = train_predict(mode, X_train, y_train, X_test)
            print("Predictions: \n", y_pred)
            # Include predicted values in the indices of missing column
            df = df.reset_index(drop=True)
            df.loc[nan_ixs, col] = y_pred
            # df = data
    return df

df = impute_missing(df, num_cols, 'regression')
df = impute_missing(df, cat_cols, 'classification')

Column Examined:  mpgCity
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001371 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2247
[LightGBM] [Info] Number of data points in the train set: 82584, number of used features: 24
[LightGBM] [Info] Start training from score 23.494236
Predictions:
 [21.85016185 29.00498766 27.65422046 ... 27.75816775 27.97985622
 17.51659363]
Column Examined:  mpgHighway
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001366 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2250
[LightGBM] [Info] Number of data points in the train set: 82587, number of used features: 24
[LightGBM] [Info] Start training from score 30.076719
Predictions:
 [27.76622949 29.09250328 34.28409818 ... 33.61004372 29.77736935
 23.88152273]
Column Examined:  horsepower
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001246 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2250
[LightGBM] [Info] Number of data points in the train set: 81661, number of used features: 24
[LightGBM] [Info] Start training from score 232.488740
Predictions:
 [271.29028202 218.76736715 211.62953147 ... 196.53088246 255.72500377
 209.66021031]
Column Examined:  horsepowerRpm
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001363 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2387
[LightGBM] [Info] Number of data points in the train set: 80955, number of used features: 24
[LightGBM] [Info] Start training from score 5870.812859
Predictions:
 [6038.79495101 5910.30488582 5987.27790116 ... 5954.06055852 5370.46403447
 5963.08102761]
Column Examined:  engineSize
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001321 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2704
[LightGBM] [Info] Number of data points in the train set: 86015, number of used features: 24
[LightGBM] [Info] Start training from score 2.569196
Predictions:
 [ 2.3393466   3.47470102  2.76335442  1.86419973  2.68771204 -0.00838381
  2.00761293  2.0022944   2.0344782   1.93045004]
Column Examined:  engineTorque
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001467 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2352
[LightGBM] [Info] Number of data points in the train set: 81483, number of used features: 24
[LightGBM] [Info] Start training from score 235.179461
Predictions:
 [278.99976221 236.31943445 201.25419988 ... 221.1849181  307.7014635
 234.76368051]
Column Examined:  engineTorqueRpm
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001161 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2366
[LightGBM] [Info] Number of data points in the train set: 80187, number of used features: 24
[LightGBM] [Info] Start training from score 3443.391198
Predictions:
 [3601.59882245 1717.4791389  2198.02116517 ... 1681.18908543 3755.88897724
 2348.31775338]
Column Examined:  featureScore
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000943 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 2893
[LightGBM] [Info] Number of data points in the train set: 77265, number of used features: 24
[LightGBM] [Info] Start training from score 6.729813
Predictions:
 [3.99594843 5.29287266 3.84030081 ... 6.95914019 6.76097381 7.27301416]
Column Examined:  body
[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.001346 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 3145
[LightGBM] [Info] Number of data points in the train set: 86024, number of used features: 24
[LightGBM] [Info] Start training from score -4.593888
[LightGBM] [Info] Start training from score -3.882517
[LightGBM] [Info] Start training from score -9.752944
[LightGBM] [Info] Start training from score -5.724027
[LightGBM] [Info] Start training from score -6.180598
[LightGBM] [Info] Start training from score -5.924302
[LightGBM] [Info] Start training from score -8.226887
[LightGBM] [Info] Start training from score -7.142874
[LightGBM] [Info] Start training from score -7.219247
[LightGBM] [Info] Start training from score -8.417943
[LightGBM] [Info] Start training from score -7.865874
[LightGBM] [Info] Start training from score -8.964486
[LightGBM] [Info] Start training from score -7.512234
[LightGBM] [Info] Start training from score -2.555808
[LightGBM] [Info] Start training from score -4.331524
[LightGBM] [Info] Start training from score -9.059797
[LightGBM] [Info] Start training from score -3.363710
[LightGBM] [Info] Start training from score -5.403957
[LightGBM] [Info] Start training from score -4.235491
[LightGBM] [Info] Start training from score -1.500081
[LightGBM] [Info] Start training from score -0.553139
[LightGBM] [Info] Start training from score -4.171706
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf
[LightGBM] [Warning] No further splits with positive gain, best gain: -inf

In [13]:
missing_vals_2 = missing_values_table(df)
missing_vals_2

# df.head()

Your selected dataframe has 25 columns.
There are 0 columns that have missing values.

Empty DataFrame
Columns: [Missing Values, % of Total Values]
Index: []

In [14]:
df.to_csv('imputed_data.csv', index=False)

### Keep AND remove data with missing values and run two separate analyses
### Check Random Forest Feature Importance on both
### Check difference in model predictions on both
### Do something with the high VIF variables (check again after imputation)